name: mdd_bingo_game_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Added the following dependencies
  flutter_hooks: ^0.21.2
  http: ^1.4.0
  lottie: ^3.3.1
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  uuid: ^4.5.1
  flutter_webrtc: ^0.9.39
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
